welcome:
  enabled: true
  message: "&a&lWelcome &f{player} &a&lto the server!"
  broadcast: true

greetings:
  enabled: true
  reward-amount: 5000
  max-rewarded-players: 3
  reward-message: "&a&l+${amount} &ffor welcoming &a{target}!"
  already-rewarded-message: "&cYou have already been rewarded for welcoming someone!"
  max-rewards-reached-message: "&cThe maximum number of welcome rewards has been reached!"

messages:
  config-reloaded: "&aConfiguration reloaded!"
  invalid-setting: "&cInvalid setting! Available: welcome-message, reward-amount, max-rewarded-players"
  setting-updated: "&aSetting &f{setting} &aupdated to &f{value}"
  no-permission: "&cYou don't have permission to use this command!"